import Navbar from '@/Components/views/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import {Poppins} from 'next/font/google'
import Wrapper from '@/Components/shared/wrapper'

const inter = Poppins({ subsets: ['latin'] ,
weight:["400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
  title: 'Dine Market',
  description: 'Generated By M USMAN AZAM',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
        <Navbar/>
        {children}
        </Wrapper>
        </body>
    </html>
  )
}
